### ISSUE TITLE
like problems

### ISSUE THREAD

**Issue by manageC0d** [IOsonoTAN/simple-facebook-graph-api#1]
`		 $data = array(
    'id' => '1730223957216833'
  );
  $result = $facebook->api('likes')
                     ->post($data, 'json');
  echo $result;
} catch(Exception $e) {
  echo $e->getMessage();
}`
(#12) singular statuses API is deprecated for versions v2.4 and higher

How is 2.8 compared to the drag? pls code..

**Comment by IOsonoTAN** [comment]
Hello @batuhanates0,

You can choose graph version by this script.
`$facebook = new GraphAPI($accessToken, 'https://graph.facebook.com', 'v2.8');`

Thanks

**Comment by manageC0d** [comment]
not enough bro

**Comment by IOsonoTAN** [comment]
Hello @batuhanates0,
If version has already changed in your script.
I think some api on Facebook Graph API has been deprecated.

Thanks
